ontology_name: "Battery Data Format Ontology"
ontology_adjective: "battery data format"
ontology_noun: "battery data format"
ontology_abbreviation: "BDF"
ontology_uri: "https://w3id.org/battery-data-alliance/ontology/battery-data-format"
ontology_prefix: "https://w3id.org/battery-data-alliance/ontology/battery-data-format#"
ontology_description: "The application ontology for the Battery Data Alliance Battery Data Format (BDF)."

ttl_files:
  - section_title: "Battery Data Format"
    path: "battery-data-format.ttl"
output:
  inferred_ttl: "battery-data-format-inferred.ttl"
  rst_file: "docs/battery-data-format.rst"
